app/models/feed_pop_up.rb
lib/utils.rb

@baileyspace feel free to test and merge as you see fit. otherwise I will that after Jan 1.

use ETag as (optional, first) unique id in feed parser #875

---

app/assets/html/collections/show.html.slim
app/assets/javascripts/users/models.js
app/controllers/api/v1/items_controller.rb
app/models/ability.rb
app/models/user.rb
app/views/api/v1/users/me.json.rabl

addresses issue #829 
if a user is in an organization, they must have 'admin' role or be the org owner in order to delete a collection or an item.
if a user is not in an organization, they should be able to delete only their own collections and items.

Org admin can delete

---

app/assets/html/items/show.html.slim
app/assets/stylesheets/directory/base.css.scss
app/views/layouts/directory.html.slim

Social sharing - Tweet Button

---

app/assets/javascripts/angular/services/loading.js
app/assets/javascripts/directory/application.js.erb
app/views/layouts/directory.html.slim

Loading mask

---

app/assets/html/account/index.html.slim
app/assets/html/items/form.html.slim
app/assets/html/plans/_plans.html.slim
app/assets/stylesheets/directory/base.css.scss
app/controllers/api/v1/items_controller.rb
app/models/concerns/billable.rb
app/models/user.rb

addresses #900 
* allow uploads on overage if credit card is valid 
* adds overage warning on Upload
* forces all overage uploads to be Premium type (forces charge)

Overage warning

---

app/assets/html/items/form.html.slim
app/assets/javascripts/audio_files/models.js
app/assets/javascripts/items/controllers.js.erb
app/models/audio_file.rb

add item to collection via remote url

---

app/models/item.rb
lib/tasks/items.rake

Item is public

---

app/admin/audio_file.rb
app/admin/item.rb
app/admin/task.rb
app/models/audio_file.rb
app/models/task.rb
app/workers/recover_task_worker.rb

This exposes the "recover" functionality via the superadmin interface. Needs to be thoroughly tested, and really only after we truly clear the backlog of stuck tasks (and their known causes).

Recover button

---

app/assets/html/items/embed_codes.html.erb
app/assets/html/items/show.html.slim
app/assets/javascripts/audio_files/controllers.js
app/assets/javascripts/items/models.js
app/assets/stylesheets/directory/base.css.scss

Embed modal #946

---

app/views/directory/base/_authn_nav.html.slim

Commented out loading animation in nav bar

---

app/assets/html/items/form.html.slim
app/assets/javascripts/items/controllers.js.erb

support multiple remoteFileUrls including from existing item edit form

---

app/assets/javascripts/angular/services/player.js
app/assets/javascripts/directory/application.js.erb

Unmask editing

---

app/views/directory/base/_authn_footer.html.slim
app/views/directory/base/_footer.html.slim

Added a link to the dev site and changed Popcast link to the iTunes URL. Addresses #1046

Footer changes

---

app/assets/javascripts/audio_files/controllers.js
app/assets/javascripts/items/controllers.js.erb

Transcript editor fix

---

app/assets/javascripts/organizations/controllers.js

Loading while adding to organization 

---

app/models/audio_file.rb
app/models/file_storage.rb
app/views/devise/registrations/new.html.slim

No email signup

---

app/assets/html/dashboard/guest.html.slim
app/assets/javascripts/directory/application.js.erb
app/assets/javascripts/items/controllers.js.erb
app/models/audio_file.rb
app/models/file_storage.rb

Meta errors

---

app/assets/html/dashboard/about.html.slim
app/assets/stylesheets/_about.scss
app/models/audio_file.rb
app/models/file_storage.rb

About styles

---

app/assets/html/dashboard/guest.html.slim
app/assets/javascripts/angular/modules/rails-ujs.js
app/assets/javascripts/angular/services/loading.js
app/assets/stylesheets/_home.scss.erb
app/models/audio_file.rb

Newsletter home

---

app/assets/html/dashboard/team.html.slim
app/assets/html/organizations/show.html.slim
app/assets/javascripts/angular/modules/prx-upload.js
app/assets/javascripts/collections/controllers.js
app/assets/javascripts/files/controllers.js
app/assets/javascripts/organizations/controllers.js
app/assets/stylesheets/_transcripts.scss
app/assets/stylesheets/pop-up_bootstrap.scss
app/controllers/api/v1/organizations_controller.rb
app/models/organization.rb
config/routes.rb

Delete org members
